In [2]:
# Assignment 1: NumPy Basic

In [ ]:
# importing numpy library

import numpy as np

In [14]:
# 1. Create a NumPy array

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

Array: [10 20 30 40 50]


In [15]:
# 2. Perform operations : Mean, Max, Mean and Sum

print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Sum:", np.sum(arr))

Mean: 30.0
Max: 50
Min: 10
Sum: 150


In [16]:
# 3. Create two arrays and perform addition and multiplication

# Arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print("Array 1: ", arr_1)
print("Array 2: ", arr_2)

# Addition
print("Addition:", arr_1 + arr_2)

# Multiplication
print("Multiplication:", arr_1 * arr_2)

Array 1:  [1 2 3]
Array 2:  [4 5 6]
Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [19]:
# 4. Create a 3×3 matrix

matrix = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

print("3×3 Matrix:")
print(matrix)

3×3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
